### ISSUE TITLE
listCols dateFormat issue

### ISSUE THREAD

**Issue by ra6hi9** [gitbrent/SpRestLib#11]
Hello,
Thanks for your interactif collaboration, I am want to format a Date field as I get items via sprLib.List().getItems(listCols), I user listCols Obj and set date:

> {dataName:'DateFieldName',formatDate:'DATE'}

But I always get the unformatted date format

When I search in your code, there is no mention of the formatDate in getItems function.

**Comment by ra6hi9** [comment]
The same issue is for dispName option :(

**Comment by gitbrent** [comment]
Good timing.

I've created a new `sprestlib-ui` branch and moved all the form population code into it recently.

This will make it easy to develop a test suite for it and to iron out issues like these.

**Comment by gitbrent** [comment]
Ping: SpRestLib-UI has landed - Issue #12

**Comment by ra6hi9** [comment]
Hi,
Thank you for your considerable efforts, I need this option in sprLib.List().getItems(listCols), to customize the name of the columns, and the date format returned by this call
