### ISSUE TITLE
Lib folders managing

### ISSUE THREAD

**Issue by ra6hi9** [gitbrent/SpRestLib#20]
I want a direct method (instead of using sprestLib.rest), to create and edit documents library folders.

**Comment by YakQin** [comment]
I used this lib a lot since i discovered it.
i am also looking for the methods for documents library. Looking forward to the implementation!

**Comment by gitbrent** [comment]
What kind of document management features are you guys looking for?

* Upload documents to library
* Check-in/out documents
* Edit document properties
* What else?

**Comment by ra6hi9** [comment]
I add to your list

- Create new folder
- Delete a Folder
- Upload document to a Folder
- Download a document
- Download a whole folder (as zip)

Thank you

**Comment by gitbrent** [comment]
Hi @ra6hi9 

With one exception, everything here will be available in the `1.9.0` release.

As "download whole folder as .zip" is not a distinct SharePoint API method, i'm setting this one aside for now.

Thanks for the feedback!

### [File API](https://gitbrent.github.io/SpRestLib/docs/api-file.html)
### [Folder API](https://gitbrent.github.io/SpRestLib/docs/api-Folder.html)
