### ISSUE TITLE
Documentation error fixing

### ISSUE THREAD

**Issue by ra6hi9** [gitbrent/SpRestLib#21]
On this link :https://github.com/gitbrent/SpRestLib#delete-item
delete function accept the item Id as int, but this is not true as the delete function want a json object {Id : ID}
Thanks

**Comment by gitbrent** [comment]
Hi @ra6hi9,

Thanks for letting me know.  The docs were all over the place with `delete()` and `recycle()` :-)

I've updated `recycle()` to accept an object like all the other list methods.

## [Recycle Item](https://gitbrent.github.io/SpRestLib/docs/api-list.html#recycle-item)
