### ISSUE TITLE
Type definitions for sprestlib

### ISSUE THREAD

**Issue by Jandos22** [gitbrent/SpRestLib#24]
Hi, @gitbrent 

Do you plan to add type definitions for your library? 

<img width="452" alt="screenshot_01" src="https://user-images.githubusercontent.com/22619894/40722056-b5d13b56-6434-11e8-824e-0f50f6bca94f.png">

![image](https://user-images.githubusercontent.com/22619894/40721970-78814e58-6434-11e8-9f2a-15d00c2b4d9d.png)

**Comment by gitbrent** [comment]
Update: Created new branch for type defs work: [type-defs-issue24](https://github.com/gitbrent/SpRestLib/tree/type-defs-issue24)

**Comment by gitbrent** [comment]
Hi @Wireliner ,

My initial pass at a definitions file is now available on the dev branch.  It worked for me using Atom and the Typescript plugin.

Let me what you think.

[sprestlib.d.ts](https://github.com/gitbrent/SpRestLib/blob/type-defs-issue24/dist/sprestlib.d.ts)

**Comment by Wireliner** [comment]
Hi @gitbrent ,

Great enhancement to SpRestLib! I tested them just now with VS Code. 

I also made a pull request as I think all list and rest methods should return Promise, user method options input should (?) be optional. You may update other places where Promise is needed. 

I also get an error: 

![image](https://user-images.githubusercontent.com/22619894/41806065-bd42f194-76d7-11e8-9d11-e6d950393151.png)

It only works after adding "new" in front. Honestly, I am still a beginner in programming, so not sure what exactly is the case of an issue. 

Regards, 
Zhandos

**Comment by gitbrent** [comment]
I've updated the typedefs and verified `user` is setup like the other classes, so hopefully that issue is resolved.
