### ISSUE TITLE
sprLib.user(options).profile() using "post" ?

### ISSUE THREAD

**Issue by YakQin** [gitbrent/SpRestLib#30]
Hello,

I run below query but I saw it is a "POST" action and I got error: 

"error":{"code":"-2130575251, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The security validation for this page is invalid and might be corrupted. Please use your web browser's Back button to try your operation again."}}}

I tried to add the digest token but it did not work.

I used this API before but I used the "GET" Method and it worked for me.

//////////////////////////////
	sprLib.user({
		baseUrl: 'https://xxxx.sharepoint.com/teams/StrategyandPOA',
		email: 'gui-zhong.qin@xxx.com',
	}).profile().then(function (objUser) {
		console.log(objUser)
	});

![capture](https://user-images.githubusercontent.com/17231180/42760506-375c386c-88fa-11e8-9a4a-0ba535f1bd2b.PNG)

**Comment by gitbrent** [comment]
Hi @YakQin ,

So, the `profile()` method attempts to get info from the UserProfile service, and that requires a POST type:

```
return sprLib.rest({
    url: "_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)?@v='"+userAcctName+"'",
    type: 'POST',
    metadata: false
});
```

However, I had not considered the session timeout aspect of doing a POST...

Let me add the ability to pass a digestToken.  I may also make it optional to get UserProfile properties instead of doing ia automatically...

**Comment by YakQin** [comment]
thanks a lot, but why you preferred "post" while "get" is working
see: https://msdn.microsoft.com/en-us/library/office/dn790354.aspx#bk_PeopleManagerGetPropertiesFor

**Comment by gitbrent** [comment]
Good catch - I have no idea why a POST was being used for that particular call...??

The userProfile call is now a GET like all the others, so auth shouldn't be an issue anymore.

Thanks!
