### ISSUE TITLE
site url cannot be called in user() method after introduction of "sprLib.baseUrl()"

### ISSUE THREAD

**Issue by YakQin** [gitbrent/SpRestLib#31]
Hello,

in issue# 8 (https://github.com/gitbrent/SpRestLib/issues/8) we discussed to add the site url to the user methods, and It work at that time but it seems this is no long working after you introduced the "sprLib.baseUrl()"

error from console: 
Warning: Check your options! Available `user()` options are: `id`,`email`,`login`,`title` 
```
var siteUrl = 'https://xxx.sharepoint.com/teams/xxx'
sprLib.user({
	baseUrl: siteUrl
}).info().then(function (objUser) {
	console.log(objUser)
});
```
>>>>>>>>>>>>>>>>>>>>>>>>>
however this is working
```
sprLib.baseUrl('https://xxx.sharepoint.com/teams/xxxx');
sprLib.user().info().then(function (objUser) {
	console.log(objUser)
});
```

**Comment by gitbrent** [comment]
Thanks @YakQin .

### Option parsing and message updated:
`sprLib.user({ junk:'test' }).info().then(obj => console.log(obj))`

Result:
"Warning: Unknown option(s) passed. Available `user()` options are: `baseUrl`,`id`,`email`,`login`,`title`"

### The `baseUrl` option is honored now:
`sprLib.user({ baseUrl:'/issue31' }).groups().then(obj => console.log(obj))`

Result: (same outcome when a full URL is used)
```
DEMO_SpRestLib.aspx:1 Uncaught (in promise) (404) 
URL used: /issue31/_api/Web/CurrentUser?$select=Groups/Id[...]
```

**Comment by YakQin** [comment]
@gitbrent ， thanks a lot for the quick fix. I downloaded the latest version and it worked.
