### ISSUE TITLE
standalone call for "UserProfileProperties"

### ISSUE THREAD

**Issue by YakQin** [gitbrent/SpRestLib#38]
Hi,
again this is a great library!

if I only need the "UserProfileProperties" the call will return all other "Person Properties" though the API will return only "UserProfileProperties" with  function sprLib.user(options).profile('UserProfileProperties')

from the performance perspective the call returns a lot of info that we don't need, especially when the user has many peers or direct reports etc. If possible you may create a standalone function for UserProfileProperties only with below query :

Url = "https://xx.sharepoint.com/teams/3wuam/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)/UserProfileProperties?@v='i:0%23.f|membership|" + mailID + "'"

with above query we can get the UserProfileProperties much faster

just a suggestion but the existing functions are already great to go with :)

**Comment by gitbrent** [comment]
Hi @YakQin 

The library already has the ability to query a single profile property (as opposed to all of them) - is this what you're looking for?

`sprLib.user().profile('PictureUrl')`

```
.--------------------------------------------------------------------------------------------------------------------------------------.
| Prop Name  |                                                       Prop Value                                                        |
|------------|-------------------------------------------------------------------------------------------------------------------------|
| PictureUrl | "https://BLAH-my.sharepoint.com:443/User%20Photos/Profile%20Pictures/admin_me_onmicrosoft_com_MThumb.jpg?t=63631247080" |
'--------------------------------------------------------------------------------------------------------------------------------------'
```

It runs the query you show in the "URL" above:

![screen shot 2018-11-27 at 22 26 48](https://user-images.githubusercontent.com/7218970/49129174-44506080-f294-11e8-8480-156766b72596.png)

**Comment by YakQin** [comment]
to make long story short, if I want to get the "Department" and if I run query sprLib.user(options).profile("UserProfileProperties"), the query will all return "Peers", "DirectReports" etc, however I don't need those details. so the query returns a lot of data that is not needed. we have a waste here.
If we have standalone query to only return "UserProfileProperties", then it is more clear when we only need part of "UserProfileProperties"
As a workaround, I used below:

		function getOrg(mailID, obj) {
			sprLib.rest({
					url: siteUrl + "/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)/UserProfileProperties?@v='i:0%23.f|membership|" + mailID + "'"
				})
				.then(function (arrItems) {
					var props = arrItems[0].UserProfileProperties.results
					$.each(props, function (i, prop) {
						if (prop.Key == 'Department') {
							obj.html(prop.Value)
						}
					})
				})
				.catch(function (errMsg) {})
		}

**Comment by YakQin** [comment]
Adding only the url
url: siteUrl + "/_api/SP.UserProfiles.PeopleManager/GetPropertiesFor(accountName=@v)/UserProfileProperties?@v='i:0%23.f|membership|" + mailID + "'"

**Comment by gitbrent** [comment]
Gotcha: Just query what we need, not the entire result set.

So, even better than pulling all `UserProfileProperties` and filtering out what was requested, the REST API allows for a call to a single profile property ([MSDN](https://msdn.microsoft.com/en-us/library/office/dn790354.aspx#bk_PeopleManagerGetUserProfilePropertyFor)).

This is the call i've implemented, it's super efficient and the smallest possible network footprint.

In the case of multiple properties, then your code above is used as there is no equivalent to `GetUserProfilePropertyFor` for multiple properties.

![screen shot 2018-12-02 at 16 17 38](https://user-images.githubusercontent.com/7218970/49352613-6a07ac00-f67e-11e8-8a53-079f58f72700.png)

![screen shot 2018-12-02 at 16 17 50](https://user-images.githubusercontent.com/7218970/49352650-9ae7e100-f67e-11e8-8dc2-6f1eac600445.png)

![screen shot 2018-12-02 at 16 18 03](https://user-images.githubusercontent.com/7218970/49352617-70962380-f67e-11e8-8002-e61bf7f27bc5.png)

**Comment by YakQin** [comment]
This is perfect ! thanks a lot
