### ISSUE TITLE
Set default "queryLimit" to 1000

### ISSUE THREAD

**Issue by YakQin** [gitbrent/SpRestLib#39]
In the early versions (e.g. 1.4.0-beta) you have set default "queryLimit" to 1000 using "'$top=' + ( inObj.queryLimit ? inObj.queryLimit : APP_OPTS.maxRows );" but now this has been dropped in the last version. I understood you want to align with the default sharepoint behavior, however this is something we often forget and in most of the case we want to set the limit more than 100. So we have to give this parameter for each call , or if we forget users will only see 100 items and the issue would be reported sooner after we deploy the app. 

If we still have 1000 as default value life will be much earlier for us :-) Because we don't need to take care of this (in most of the cases 1000 items can meet the needs). Maybe I am talking about my particular environment where we don't work with huge items in SP.

**Comment by gitbrent** [comment]
Hi @YakQin 

This is a tough one.  I make the mistake of not including `queryLimit` all the time, but the other side of the coin is that pulling back 1,000 (or whatever default) number of items can be a performance drag.

Anyone using the library for things like people-pickers would not be a fan of pulling so much data back at a keystroke.

The only solution that I can think of that's not invasive or punitive is allowing a default `queryLimit` at the library level, like we currently have for `baseUrl`... ?

**Comment by YakQin** [comment]
Hello,
Agree with you, let's keep the current design. Actually we also do a lot of copy-and-paste in coding, we can just give this parameter to the SP query once, next time we can copy the lines for the SP query that already has the queryLimit parameter, then we just modify based on the actual requirements.
I also use people-pickers a lot. great feature !

**Comment by gitbrent** [comment]
I've added a new `options()` method.

It has a new option to allow `queryLimit` to be set globally - so every `sprlib` query will use this default value if no `queryLimit` is provided, which should help to eliminate the original issue.

```javascript
sprLib.options({
    queryLimit:1000
});
```
```
.----------------------------.
|  Prop Name  |  Prop Value  |
|-------------|--------------|
| baseUrl     | ..           |
| nodeCookie  | (null/undef) |
| nodeEnabled | false        |
| nodeServer  | (null/undef) |
| queryLimit  | 1000         |
'----------------------------'
```
