### ISSUE TITLE
Paging capability

### ISSUE THREAD

**Issue by Wireliner** [gitbrent/SpRestLib#4]
Hello! 

How is it possible to access __next property for pagination using List methods? I couldn't find any hints for paging in sprestlib documentation. API is really lightweight and very handy, it would be great to have paging options as well. 

Regards, 
Zhandos

**Comment by gitbrent** [comment]
Hi @Wireliner,

Thanks for opening this request.

I've been focusing on completing and stabilizing the core API features, which is nearing completion.  Once i've got the last `site()` method working, I was planning to turn my attention to paging.

Bottom line: Paging (`__next`) feature is coming very soon.

Thanks for the feedback!  I'll update this Issue as progress on paging is made.

**Comment by Wireliner** [comment]
Hi @gitbrent! Very glad to hear that. Thanks for the great job!

**Comment by gitbrent** [comment]
Hi @Wireliner,

I've added a new option to `getItems()` that implements SharePoint's next/skip/paging feature.

See the README for an example of `queryNext` and let me know what you think.
