### ISSUE TITLE
Demo doesn't work from sub-folder off sitepages

### ISSUE THREAD

**Issue by DavidPratten** [gitbrent/SpRestLib#46]
Hi 

Small detail, if the sprestlib-demo.html is added in a subfolder of sitepages and then made available through an demo.aspx in the same folder API accesses fail with 404 errors.

David

**Comment by gitbrent** [comment]
Thanks @DavidPratten !

I'd neglected to update the default (`baseUrl`) URL.  The correct value is being read from `_spPageContextInfo` now, so nesting no longer causes an issue.
