### ISSUE TITLE
Error in list('listname').create({data})

### ISSUE THREAD

**Issue by Wireliner** [gitbrent/SpRestLib#5]
Good day! 

When I try to create an item in a list I get the following error: 

> 400 - {"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"A node of type 'EndOfInput' was read from the JSON reader when trying to read the start of an entry. A 'StartObject' node was expected."}}}

````
const body = {
                Name: action.userData.name,
                Surname: action.userData.surname,
                Alias: action.userData.alias,
                Gin: action.userData.gin,
                Location: action.userData.location,
                Email: action.userData.email
            };
            return sprLib.list('NgPeople').create(body);
````

I guess it is related to sending 'data' or 'body' object during request. 

Regards, 
Zhandos

**Comment by gitbrent** [comment]
Hi @Wireliner,

Thanks for opening an issue.

It appears the JSON `body` object isn't being encoded correctly... Can you check the dev tools (F12) Network tab to see what's being passed to SP?

![screen shot 2017-11-28 at 23 32 39](https://user-images.githubusercontent.com/7218970/33359573-1235a0ba-d495-11e7-9839-f4a12418bc7d.png)

**Comment by Wireliner** [comment]
Hi @gitbrent ,

Looks like no payload is being passed. Btw I use sp-rest-proxy for development (2nd picture). 

<img width="524" alt="issue5" src="https://user-images.githubusercontent.com/22619894/33361451-0defaed2-d4fa-11e7-8984-13d2d67e18e6.png">

<img width="547" alt="issue5_console" src="https://user-images.githubusercontent.com/22619894/33361464-1480896a-d4fa-11e7-8e59-51172d47b780.png">

**Comment by koltyakov** [comment]
@Wireliner,

Can you check the same script/payload on SharePoint page and with `sp-rest-proxy`?
Is there a difference? Feel free to post related issues to proxy's project if there is a different behavior on SP page and Local page talking to the proxy.

**Comment by Wireliner** [comment]
Privet @koltyakov,

After running script on Sharepoint I get a different error and again don't see payload being passed to SP. 

![1](https://user-images.githubusercontent.com/22619894/33364318-b64e3e3a-d505-11e7-9328-900792fbea99.png)

![2](https://user-images.githubusercontent.com/22619894/33364286-8d702bd6-d505-11e7-8ad3-8ffedd22b0d8.png)

**Comment by koltyakov** [comment]
Does `SpRestLib` wrap digests?
@Wireliner please try refreshing the page. The error is common when you navigate back and forth in browsers history and then execute POST with the wrong digest.

**Comment by Wireliner** [comment]
@koltyakov refreshed the page, same error. 

not sure if SpRestLib wraps digests ... I am quite new to SP, but my custom POST call to add item using REST api works fine, just wanted to take advantage of simlicity of SpRestLib.

**Comment by gitbrent** [comment]
Hi @Wireliner,

SpRestLib does pass the security token/digest value - it's one if the last items under the "Request Headers" section:

![screen shot 2017-11-29 at 20 38 31](https://user-images.githubusercontent.com/7218970/33410772-6fcca428-d547-11e7-967e-ae4655ca5b19.png)

However, this depends upon the SP page having the `__REQUESTDIGEST` form element.  Normally, you'd embed an app in an .aspx page within a Webpart, where this token will always be present.  Check for the token via `$('#__REQUESTDIGEST').length` etc.

Your second post's screencap shows the URL being used as:
```javascript
http://localhost:4200/_api/list/getbytitle[...]
```

So the issue there may be due to an incorrect value.  Perhaps, use the baseUrl variable:
```javascript
sprLib.list({ listName:'Employees', baseUrl:'/sites/wireline' })
```

**Comment by Wireliner** [comment]
@gitbrent thanks for clear explanation. I see now that the problem maybe is that I use my custom ".html" page and not ".aspx" page, so digest value could not be retrieved in this case. What I do is get FDV by calling to "_api/contextinfo".

**Comment by gitbrent** [comment]
Hi @Wireliner,

Thanks for the follow-up, that's really helpful.

The library currently only looks for the FDV via the `__REQUESTDIGEST` form element, but that leaves people who use the `_api/contextinfo` without an avenue to auth via SpRestLib...

I'll create a new option to pass the FDV value in the next release.

**Comment by gitbrent** [comment]
Thanks for your help @Wireliner!

**Comment by lazhar0bacha** [comment]
Good day!

When I try to create an item in a list I get the following error (it is the same errors for Wireliner) :
![git1](https://user-images.githubusercontent.com/35800414/36636376-7f91ed92-197a-11e8-9dae-7f729ef90f60.png)

and there is my code:

 sprLib.list({ name: 'UserData', baseUrl: '/sites/SiteDev/SharePoint-Hosted-AddIn-Alight'})
            .create({
                __metadata: { type: "SP.Data.UserDataListItem" },
                "Firstname": userData[0].Firstname,
                "Lastname": userData[0].Lastname,
                "Location": userData[0].Location,
                "Address": userData[0].Address,
                "City": userData[0].City,
                "Country": userData[0].Country,
                "Zip": userData[0].Zip,
                "Phone": userData[0].Phone,
                "Birthdate": userData[0].Birthdate,
                "Comments": userData[0].Comments,
                "Mail": userData[0].Mail,
                "Position": userData[0].Position,
            })

PS: for my example I used "Office UI Fabric React"

Regards,

**Comment by gitbrent** [comment]
Hi @lazhar0bacha,

Since you're also encountering authentication issues, i created a whole new section to cover this in the README.  Hopefully, this will really help when errors like this come up.

Check out the [SharePoint Authentication Notes](https://github.com/gitbrent/SpRestLib#sharepoint-authentication-notes) section and let me know if that helps...

**Comment by lazharbacha** [comment]
Hi @gitbrent 

Thank you so much for your help, it works for me 👍 
and this is my code maybe it will be helpful for someone else.

 const user = {

            "FirstName1": userData[0].Firstname,
            "Lastname": userData[0].Lastname,
            "Birthdate": userData[0].Birthdate,
            "Address": userData[0].Address,
            "Zip": userData[0].ZIP,
            "City": userData[0].City,
            "Country": userData[0].Country,
            "Mail": userData[0].Mail,
            "Phone": userData[0].Phone,
            "Position": userData[0].Position,
            "Location1": userData[0].Location,
            "Title": userData[0].Salutation,
            "AcceptTerm": userData[0].AcceptTerm,
            "Comments1": userData[0].Comments,
        };
       
        sprLib.nodeConfig({ nodeEnabled: false });
        sprLib.rest({ url: '_api/contextinfo', type: 'POST' })
            .then(arr => {
                let strReqDig = arr[0].GetContextWebInformation.FormDigestValue;
                return sprLib.list({ name: 'User', requestDigest: strReqDig }).create(user);
            })
            .then(obj => {
                console.log('Item created!');
            });
