### ISSUE TITLE
'listGUID' not supported when with  ‘baseUrl’

### ISSUE THREAD

**Issue by YakQin** [gitbrent/SpRestLib#7]
Hello,
I like this lib very much. 
but it seems the following is not support right now. I wanted to always use the GUID because the list title can be changed by others.

sprLib.list({ listGUID:"the GUID", baseUrl:"the url" }).getItems...

**Comment by gitbrent** [comment]
Hi @YakQin,

Thanks for the feedback - I hope you find the library useful.

You'll want to use the `name` option for the List GUID (it takes both name or GUID - [doc link](https://github.com/gitbrent/SpRestLib#listlibrary-methods-splist))

```javascript
sprLib.list({ name:"8fda2798-dbbc-497d-9876-ef87b08e09e1", baseUrl:"the url" }).getItems()
sprLib.list({ name:"Departments", baseUrl:"the url" }).getItems()
```

Let me know if you have any other issues or questions.

Example:
![screen shot 2017-12-31 at 17 56 58](https://user-images.githubusercontent.com/7218970/34464740-1f7fc60a-ee54-11e7-8c07-d37ca530bb34.png)

**Comment by YakQin** [comment]
thanks for the quick response. it is clear now. I should read the doc more carefully :)
by intuition I thought if I give "name" I should enter the list name only. 

Maybe if you change to "GUID" for GUID then it will be much more clear like below
sprLib.list({ GUID:"8fda2798-dbbc-497d-9876-ef87b08e09e1", baseUrl:"the url" }).getItems()

**Comment by gitbrent** [comment]
Thanks for the feedback @YakQin 

I've added the ability to pass guid as `guid` option now:

![screen shot 2018-01-05 at 22 44 27](https://user-images.githubusercontent.com/7218970/34636602-195a859c-f26b-11e7-90b1-57bbf18bf4a7.png)
