### ISSUE TITLE
Error in list('listname').create({data})

### ISSUE THREAD

**Issue by ra6hi9** [gitbrent/SpRestLib#9]
Hello,
I am facing the same problem as discussed on issue #5, I am using SpRestLib in a Sharepoint hosted app, into the default.aspx page, when making GET calls no problem, but when I call list('listname').create({data}),
with data as JSON object {name:"test", ...}, I get an error about page validation etc,  in devtools I noted that there is no X-RequestDigest nor Payload in the post call.
![image](https://user-images.githubusercontent.com/2559570/34590319-eb201fba-f1ad-11e7-8394-6ae2b5f724b6.png)

 How can I resolve the issue as there is no solution mentioned in the previous discussion #5 ?
Thanks in advance

**Comment by gitbrent** [comment]
Hi @ra6hi9,

Good timing - I just finished updating this information in the README this evening. :-)

Check out the `requestDigest` option in the [List Options section](https://github.com/gitbrent/SpRestLib#listlibrary-methods-splist).

Providing a value to that option will result in the `X-RequestDigest` header being populated and sent to SP enabling CRUD operations.

**Comment by ra6hi9** [comment]
Thanks brent,
This new option is very helpful, but this resolve only a part of the issue, because even if I am making the create operation from a SharePoint .aspx page with $("#__REQUESTDIGEST").val() not empty, I am getting the same error (validation ...)
After I did some debugging I found the source of the issue:

> // Detect Node.js
> var NODEJS = ( typeof module !== 'undefined' && module.exports );
> ...
> ...
> if ( NODEJS ) {
> 						objAjaxQuery.headers["Cookie"] = APP_OPTS.nodeCookie;
> 						delete objAjaxQuery.headers["X-RequestDigest"]; //<---- 
...

The X-RequestDigest header is removed if the code is executed in NODE context, but this code is also executed in Browser context, because NODEJS variable is not undefined, can you correct me if I misunderstood something.

Thanks

**Comment by gitbrent** [comment]
Hi @ra6hi9 

Yes, Angular and other types of applications may be detected as Node.js apps, so i've created a flag that will you enable to specify browser mode:

[NODE Options](https://github.com/gitbrent/SpRestLib#integration-with-angulartypescriptwebpack)

`sprLib.nodeConfig({ nodeEnabled:false });`

That should enable X-RequestDigest to pass as normal.

**Comment by ra6hi9** [comment]
I think this condition in inverted:

> sprLib.nodeConfig({ nodeEnabled:false });
....
> if ( NODEJS && !APP_OPTS.nodeEnabled ) {

if nodeEnabled == false -> APP_OPTS.nodeEnabled == false -> NODEJS && !APP_OPTS.nodeEnabled == true

Thank you

**Comment by ra6hi9** [comment]
The inverted condition issue is resolved in the last commits 👍
